name=Mango

ascii_1="""
   _____                               __      __  _____
  /     \ _____    ____    ____   ____/  \    /  \/     \
 /  \ /  \\__  \  /    \  / ___\ /  _ \   \/\/   /  \ /  \
/    Y    \/ __ \|   |  \/ /_/  >  <_> )        /    Y    \
\____|__  (____  /___|  /\___  / \____/ \__/\  /\____|__  /
        \/     \/     \//_____/              \/         \/
"""

ascii_2="""
 .----------------.  .----------------.  .-----------------. .----------------.  .----------------.  .----------------.  .----------------.
| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
| | ____    ____ | || |      __      | || | ____  _____  | || |    ______    | || |     ____     | || | _____  _____ | || | ____    ____ | |
| ||_   \  /   _|| || |     /  \     | || ||_   \|_   _| | || |  .' ___  |   | || |   .'    `.   | || ||_   _||_   _|| || ||_   \  /   _|| |
| |  |   \/   |  | || |    / /\ \    | || |  |   \ | |   | || | / .'   \_|   | || |  /  .--.  \  | || |  | | /\ | |  | || |  |   \/   |  | |
| |  | |\  /| |  | || |   / ____ \   | || |  | |\ \| |   | || | | |    ____  | || |  | |    | |  | || |  | |/  \| |  | || |  | |\  /| |  | |
| | _| |_\/_| |_ | || | _/ /    \ \_ | || | _| |_\   |_  | || | \ `.___]  _| | || |  \  `--'  /  | || |  |   /\   |  | || | _| |_\/_| |_ | |
| ||_____||_____|| || ||____|  |____|| || ||_____|\____| | || |  `._____.'   | || |   `.____.'   | || |  |__/  \__|  | || ||_____||_____|| |
| |              | || |              | || |              | || |              | || |              | || |              | || |              | |
| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
 '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'
"""

ascii_3="""
   *                                         *
 (  `                            (  (      (  `
 )\))(      )         (  (       )\))(   ' )\))(
((_)()\  ( /(   (     )\))(  (  ((_)()\ ) ((_)()\
(_()((_) )(_))  )\ ) ((_))\  )\ _(())\_)()(_()((_)
|  \/  |((_)_  _(_/(  (()(_)((_)\ \((_)/ /|  \/  |
| |\/| |/ _` || ' \))/ _` |/ _ \ \ \/\/ / | |\/| |
|_|  |_|\__,_||_||_| \__, |\___/  \_/\_/  |_|  |_|
                     |___/
"""
