---
name: Build Stable ISOs
on:
  merge_group:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/build-iso.yml"
      - ".github/workflows/reusable-build-iso-anaconda.yml"
      - "iso_files/**"
  workflow_dispatch:
    inputs:
      upload_artifacts:
        description: 'Upload ISOs as job artifacts'
        type: boolean
        default: false
      upload-to-s3:
        description: "Upload to S3"
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "0 3 * * 3" # Push to testing bucket every week at 03:00 on Wednesdays
jobs:
  build-iso-stable:
    name: Build Stable ISOs
    uses: ./.github/workflows/reusable-build-iso-anaconda.yml
    secrets: inherit
    with:
      # Upload artifacts on PR checks or if manually requested
      upload_artifacts: ${{ github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.upload_artifacts) }}
      # Upload to R2 on merge_group, scheduled runs, or if manually requested
      upload_to_s3: ${{ github.event_name == 'merge_group' || github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.upload_to_s3) }}
